version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432

  server:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379

  backend-migration:
    build:
      context: ../Backend
      dockerfile: Dockerfile.migration
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      - database

  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  auth:
    build:
      context: ../Auth
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379

  auth-migration:
    build:
      context: ../Auth
      dockerfile: Dockerfile.migration
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      - database
